### ISSUE TITLE
Fetch details of an organization

### ISSUE THREAD

**Issue by nwarwick** [nwarwick/dyte#22]
See Dyte [API documents](https://docs.dyte.io/api/#/) and existing code for reference on how to proceed. Don't hesitate to reach out with any questions!

**Comment by zainbinfurqan** [comment]
Can i Work on it please.

**Comment by nwarwick** [comment]
All yours @zainbinfurqan!

**Comment by zainbinfurqan** [comment]
@nwarwick Can you guide me how i can run this project, I already followed the read me commands,

**Comment by nwarwick** [comment]
@zainbinfurqan So you would have to actually install the gem as a dependency in a project. Since you are working on functionality that is unreleased, I think writing tests would be the best way to confirm the functionality.

**Comment by zainbinfurqan** [comment]
> @zainbinfurqan So you would have to actually install the gem as a dependency in a project. Since you are working on functionality that is unreleased, I think writing tests would be the best way to confirm the functionality.

its a server how i can run this locally to test apis/functions

**Comment by nwarwick** [comment]
1. run `bin/console`
2. Instantiate the client `client = Client.new(organization_id: '1234', api_key: '1234')`
3. Run a test command `client.participants.list(session_id: 1)`

**Comment by zainbinfurqan** [comment]
from where i can get this organization_id and api_key? @nwarwick

**Comment by nwarwick** [comment]
You will need to signup for a Dyte account: https://dyte.io/. You will also have to submit a support request to have v2 of the API enabled (unless they have started enabling it by default now)

**Comment by nwarwick** [comment]
How's the ticket coming along @zainbinfurqan? Anything I can help with?
