### ISSUE TITLE
Fetch a meeting for an organization

### ISSUE THREAD

**Issue by nwarwick** [nwarwick/dyte#25]
See Dyte [API documents](https://docs.dyte.io/api/#/) and existing code for reference on how to proceed. Don't hesitate to reach out with any questions!

**Comment by nwarwick** [comment]
Yep for sure @zainbinfurqan! Let me know if you have any questions.

**Comment by nachiket87** [comment]
https://github.com/nwarwick/dyte/blob/69feb33aa579756f14124bd392ab530878930d27/lib/dyte/resources/meetings.rb#L8-L10

Doesn't this already exist?

https://docs.dyte.io/api/#/operations/get_meeting

**Comment by nwarwick** [comment]
Yep you're right @nachiket87. Will close this.
